export const home0bj0ne = {
  id: 'about',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited     transactions without getting charged any fees.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-2.svg').default,
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
};
export const home0bjTwo = {
  id: 'discover',
  lightBg: false,
  lightText: true,
  lightTextDesc: false,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited     transactions without getting charged any fees.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-3.svg').default,
  alt: 'Car',
  dark: false,
  primary: true,
  darkText: false,
};
export const home0bjThree = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited Transactions with zero fees',
  description:
    'Get access to our exclusive app that allows you to send unlimited     transactions without getting charged any fees.',
  buttonLabel: 'Get started',
  imgStart: false,
  img: require('../../images/svg-1.svg').default,
  alt: 'Car',
  dark: false,
  primary: false,
  darkText: true,
};
